# Generated by Django 3.1.7 on 2021-03-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'get_latest_by': 'modified_time', 'ordering': ('-modified_time', '-uploaded_time')},
        ),
        migrations.RenameField(
            model_name='song',
            old_name='modified_on',
            new_name='modified_time',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='created_on',
            new_name='uploaded_time',
        ),
    ]
