# Generated by Django 3.1.7 on 2021-03-13 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210313_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('-modified_time', '-uploaded_time'),
                'get_latest_by': 'modified_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioFileType', models.CharField(choices=[('song', 'Song'), ('podcast', 'Podcast'), ('audiobook', 'AudioBook')], default='song', max_length=20)),
                ('audioFileMetadata', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('host', models.CharField(max_length=100)),
                ('participants', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'ordering': ('-modified_time', '-uploaded_time'),
                'get_latest_by': 'modified_time',
                'abstract': False,
            },
        ),
    ]
