# Generated by Django 3.1.7 on 2021-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_audiobook_audiomanager_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomanager',
            name='audioFileMetadata',
            field=models.TextField(),
        ),
    ]
