# Generated by Django 3.1.7 on 2021-03-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210313_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiomanager',
            options={'get_latest_by': 'modified_time', 'ordering': ('-modified_time', '-uploaded_time')},
        ),
        migrations.AddField(
            model_name='audiomanager',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomanager',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
