# Generated by Django 3.1.7 on 2021-03-19 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_audiomanager_audio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomanager',
            name='audio_id',
            field=models.PositiveIntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
