# Generated by Django 3.1.7 on 2021-03-19 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210319_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomanager',
            name='audio_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
